#coding: utf-8
'''
 *
 * AddMob Integradora de Soluções LTDA (c) - 2015
 * 
 * PortalERP
 *   
 * urls.py
 * 
 * Arquivo que define as URLs utilizadas no sistema 
 * 
 * Desenvolvido por: 
 * - Diego Oliveira
 * - Flávio Lucio De Paula G.JR
 * - José Eduardo Ferreira
 * - Paulo Vitor Francisco
 *
'''
from service.views import (viewIndex, viewHome, viewSobre, viewEmpresa, viewLogin, viewProduto, viewGrupo, 
    viewCliente, viewUsuario, viewTipoUsuario, viewOpcionais, viewNotaFiscalEntrada, viewNotaFiscalSaida, 
    viewParametro, viewSerie, viewRelatorioNotaFiscalEntradaSaida, viewOcorrencia, viewAtendente, viewContato, 
    viewTipoDocumento, viewTransacao, viewConsultaVendas, viewContaBancaria, viewCarteiraBancaria, 
    viewDeposito, viewRelatorioContas, viewFinanca, viewClassificacaoFiscal, 
    viewNaturezaOperacao, viewAtributo, viewRepresentante, viewConfiguracaoBoleto, viewCondicaoPagamento, 
    viewHomeAdministrativo, viewEmpresaAdministrativo, viewRelatoriosAdministrativo, viewStatus, viewConsole, 
    viewFinanceira, viewBanco, viewMovimentacaoContas, viewRetorno, viewHomeCliente, 
    viewInventario, viewMotivoInventario, viewCheque, viewPais, viewPersonalizacoes, viewCartaCorrecao, 
    viewModulo, viewFaleConosco, viewVendasProduto, viewEstado, viewCidade, viewRegiao, viewArea, viewErro404, 
    viewTipoUsuarioAdministrativo, viewFluxoCaixa, viewTela, viewEspecie, viewBismart, viewMesas, 
    viewPromocao, viewGosto, viewCupom, viewCardapioShow, viewCircuito, viewContatoDados, viewChat, viewColeta,
    viewOrdemServico, viewTipoServico, viewPontoColEnt, viewBoletoBancario, viewRemessa, viewApi, 
    viewSetor, viewComentarioProduroPedido, viewAplicativo, viewLoja, viewFormaEntrega, viewFormaPagamento,
    viewApontamentoProducao, viewCategoria, viewStatusFinalizacao, viewTipoAtendimento, viewAppBase, viewOpcionaisTestes)
from service.utilitarios import funcoes
from service.gerenciador_imagens import viewGerenciadorImagens
from service.exportador_sql import viewExportadorSql
from django.conf.urls import url
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = [
    url(r'^$', viewIndex.index, name='index'),
    url(r'^enviar_mensagem_entrar_contato$', viewIndex.enviar_mensagem_entrar_contato, 
        name='enviar_mensagem_entrar_contato'),
    # Página Inicial
    url(r'^home$', viewHome.home, name='home'),
    # Calculadora tributária
    url(r'^calculadora_tributaria$', viewHome.calculadora_tributaria, name='calculadora_tributaria'),
    # Sobre
    url(r'^sobre$', viewSobre.sobre, name='sobre'),
    # Dados da Empresa
    url(r'^dados_empresa$', viewEmpresa.dados_empresa, name='dados_empresa'),
    url(r'^salvar_dados_empresa$', viewEmpresa.salvar_dados_empresa, name='salvar_dados_empresa'),
    url(r'^consultar_cnpj_empresa$', viewEmpresa.consultar_cnpj_empresa, name='consultar_cnpj_empresa'),
    url(r'^sincronizar_skyhub$', viewEmpresa.sincronizar_skyhub, name='sincronizar_skyhub'),
    url(r'^sincronizar_madeira$', viewEmpresa.sincronizar_madeira, name='sincronizar_madeira'),
    url(r'^sincronizar_leroy$', viewEmpresa.sincronizar_leroy, name='sincronizar_leroy'),
    url(r'^empresas$', viewEmpresa.empresas, name='empresas'),
    url(r'^inativar_empresa$', viewEmpresa.inativar_empresa, name='inativar_empresa'),
    url(r'^pesquisar_empresa$', viewEmpresa.pesquisar_empresa, name='pesquisar_empresa'),
    url(r'^obter_campos_empresa$', viewEmpresa.obter_campos_empresa, name='obter_campos_empresa'),
    url(r'^consultar_codempresa$', viewEmpresa.consultar_codempresa, name='consultar_codempresa'),
    url(r'^gerar_codempresa$', viewEmpresa.gerar_codempresa, name='gerar_codempresa'),
    # Pesquisa páginas do site
    url(r'^pesquisar$', viewHome.pesquisar, name='pesquisar'),
    # Login
    url(r'^login$', viewLogin.login_usuario, name='login'),
    url(r'^login_view$', viewLogin.login_view, name='login_view'),
    url(r'^logout$', viewLogin.logout_view, name='logout'),
    url(r'^obter_usuario_logado$', viewLogin.obter_usuario_logado, name='obter_usuario_logado'),
    url(r'^recuperar_senha$', viewLogin.recuperar_senha, name='recuperar_senha'),
    url(r'^enviar_codigo$', viewLogin.enviar_codigo, name='enviar_codigo'),
    url(r'^fornecer_nova_senha$', viewLogin.fornecer_nova_senha, name='fornecer_nova_senha'),
    url(r'^gerar_senha_recuperacao$', viewLogin.gerar_senha_recuperacao, name='gerar_senha_recuperacao'),
    url(r'^verificar_senha_recuperacao$', viewLogin.verificar_senha_recuperacao, 
        name='verificar_senha_recuperacao'),
    url(r'^alterar_senha$', viewLogin.alterar_senha, name='alterar_senha'), 
    # Produtos
    url(r'^produto$', viewProduto.produto, name='produto'),
    url(r'^novo_produto$', viewProduto.novo_produto, name='novo_produto'),
    url(r'^cadastrar_produto$', viewProduto.cadastrar_produto, name='cadastrar_produto'),
    url(r'^cadastrar_produto_nf_entrada$', viewProduto.cadastrar_produto_nf_entrada, 
        name='cadastrar_produto_nf_entrada'),
    url(r'^inativar_produtos$', viewProduto.inativar_produtos, name='inativar_produtos'),
    url(r'^obter_relatorio_produto$', viewProduto.obter_relatorio_produto, name='obter_relatorio_produto'),
    url(r'^obter_id_produto$', viewProduto.obter_id_produto, name='obter_id_produto'),
    url(r'^pesquisar_produto$', viewProduto.pesquisar_produto, name='pesquisar_produto'),
    url(r'^obter_campos_produto$', viewProduto.obter_campos_produto, name='obter_campos_produto'),
    url(r'^relatorio_produto$', viewProduto.relatorio_produto, name='relatorio_produto'),
    url(r'^obter_sub_grupos$', viewProduto.obter_sub_grupos, name='obter_sub_grupos'),
    url(r'^filtrar_relatorio_produtos$', viewProduto.filtrar_relatorio_produtos, 
        name='filtrar_relatorio_produtos'),
    url(r'^filtrar_relatorio_produtos_loja$', viewProduto.filtrar_relatorio_produtos_loja, 
        name='filtrar_relatorio_produtos_loja'),
    url(r'^filtrar_relatorio_produto_categoria$', viewProduto.filtrar_relatorio_produto_categoria, 
        name='filtrar_relatorio_produto_categoria'),
    url(r'^consultar_produto$', viewProduto.consultar_produto, name='consultar_produto'),
    url(r'^pesquisar_produto_fornecedor$', viewProduto.pesquisar_produto_fornecedor, 
        name='pesquisar_produto_fornecedor'),
    url(r'^pesquisar_produto_codbarra$', viewProduto.pesquisar_produto_codbarra, 
        name='pesquisar_produto_codbarra'),
    url(r'^analise_produto$', viewProduto.analise_produto, name='analise_produto'),
    url(r'^relatorio_analise_produto$', viewProduto.relatorio_analise_produto, 
        name='relatorio_analise_produto'),
    url(r'^importar_produto$', viewProduto.importar_produto, name='importar_produto'),
    url(r'^importar_planilha_produto$', viewProduto.importar_planilha_produto, 
        name='importar_planilha_produto'),
    url(r'^consultar_codigo_barras$', viewProduto.consultar_codigo_barras, name='consultar_codigo_barras'),
    url(r'^pesquisar_produto_cliente_servico$', viewProduto.pesquisar_produto_cliente_servico, 
        name='pesquisar_produto_cliente_servico'),
    url(r'^obter_campos_produto_cliente_servico$', viewProduto.obter_campos_produto_cliente_servico, 
        name='obter_campos_produto_cliente_servico'),
    # Produto categoria
    url(r'^cadastrar_produto_categoria$', viewProduto.cadastrar_produto_categoria, 
        name='cadastrar_produto_categoria'),
    url(r'^informacoes_produto_categoria$', viewProduto.informacoes_produto_categoria, 
        name='informacoes_produto_categoria'),
    url(r'^remover_produto_categoria$', viewProduto.remover_produto_categoria, 
        name='remover_produto_categoria'),
    # Grupos
    url(r'^grupo$', viewGrupo.grupo, name='grupo'),
    url(r'^cadastrar_grupo$', viewGrupo.cadastrar_grupo, name='cadastrar_grupo'),
    url(r'^obter_id_grupo$', viewGrupo.obter_id_grupo, name='obter_id_grupo'),
    url(r'^gravar_posicoes$', viewGrupo.gravar_posicoes, name='gravar_posicoes'),
    url(r'^valida_nome$', viewGrupo.valida_nome, name='valida_nome'),
    url(r'^pesquisar_grupo$', viewGrupo.pesquisar_grupo, name='pesquisar_grupo'),
    url(r'^obter_campos_grupo$', viewGrupo.obter_campos_grupo, name='obter_campos_grupo'),
    url(r'^inativar_grupo$', viewGrupo.inativar_grupo, name='inativar_grupo'),
    url(r'^listar_grupos$',viewGrupo.listar_grupos,name="listar_grupos"),
    # Cliente    
    url(r'^cliente$', viewCliente.cliente, name='cliente'),
    url(r'^novo_cliente$', viewCliente.novo_cliente, name='novo_cliente'),
    url(r'^cadastrar_cliente$', viewCliente.cadastrar_cliente, name='cadastrar_cliente'),
    url(r'^cadastrar_cliente_cardapioshow$', viewCliente.cadastrar_cliente_cardapioshow, 
        name='cadastrar_cliente_cardapioshow'),
    url(r'^inativar_clientes$', viewCliente.inativar_clientes, name='inativar_clientes'),
    url(r'^obter_relatorio_cliente$', viewCliente.obter_relatorio_cliente, name='obter_relatorio_cliente'),
    #url(r'^obter_cliente$', viewCliente.obter_cliente, name='obter_cliente'),
    url(r'^obter_id_cliente$', viewCliente.obter_id_cliente, name='obter_id_cliente'),
    url(r'^pesquisar_cliente$', viewCliente.pesquisar_cliente, name='pesquisar_cliente'),
    url(r'^obter_campos_cliente$', viewCliente.obter_campos_cliente, name='obter_campos_cliente'),
    url(r'^relatorio_cliente$', viewCliente.relatorio_cliente, name='relatorio_cliente'),
    url(r'^obter_cidades$', viewCliente.obter_cidades, name='obter_cidades'),
    url(r'^filtrar_relatorio_clientes$', viewCliente.filtrar_relatorio_clientes, 
        name='filtrar_relatorio_clientes'),
    url(r'^importar_cliente$', viewCliente.importar_cliente, name='importar_cliente'),
    url(r'^importar_planilha_cliente$', viewCliente.importar_planilha_cliente, 
        name='importar_planilha_cliente'),
    url(r'^consultar_cliente$', viewCliente.consultar_cliente, name='consultar_cliente'),
    url(r'^alterar_dados_cliente_nf$', viewNotaFiscalSaida.alterar_dados_cliente_nf, 
        name='alterar_dados_cliente_nf'),
    # Usuário
    url(r'^usuario$', viewUsuario.usuario, name='usuario'),
    url(r'^novo_usuario$', viewUsuario.novo_usuario, name='novo_usuario'),
    url(r'^novo_usuario_cadastro$', viewUsuario.novo_usuario_cadastro, name='novo_usuario_cadastro'),
    url(r'^lista_restaurante$' , viewEmpresa.listarRestaurante,name="lista_restaurante"),
    url(r'^lista_pratos$' , viewProduto.listarPratos,name="lista_pratos"),
    url(r'^post_cliente$',viewUsuario.postCliente,name="post_cliente"),
    url(r'^update_cliente$',viewUsuario.atualizandoUsuario,name="update_cliente"),
    url(r'^novo_usuario_cardapioshow$', viewUsuario.novo_usuario_cardapioshow, 
        name='novo_usuario_cardapioshow'),
    url(r'^cadastro_cupom$', viewCupom.gerarCupom, name='cadastro_cupom'),
    url(r'^listar_cupom$', viewCupom.recuperandoCupons, name='listar_cupom'),
    url(r'^listar_promocao$',viewPromocao.recebendoPromocao, name='listar_promocao'),
    url(r'^listar_gosto$',viewGosto.recebendoGosto, name='listar_gosto'),
    url(r'^log_usuario$',viewLogin.login_cardapioshow, name='login_usuario'),
    url(r'^rec_usuario$',viewLogin.recuperar_senha_cardapioshow, name='rec_usuario'),
    url(r'^recuperar_circuito$', viewCircuito.recuperarCircuito, name='recuperar_circuito'),
    url(r'^cadastrar_usuario$', viewUsuario.cadastrar_usuario, name='cadastrar_usuario'),
    url(r'^cadastrar_novo_usuario$', viewUsuario.cadastrar_novo_usuario, name='cadastrar_novo_usuario'),
    url(r'^inativar_usuarios$', viewUsuario.inativar_usuarios, name='inativar_usuarios'),
    url(r'^obter_id_usuario$', viewUsuario.obter_id_usuario, name='obter_id_usuario'),
    url(r'^consultar_username$', viewUsuario.consultar_username, name='consultar_username'),
    url(r'^pesquisar_usuario$', viewUsuario.pesquisar_usuario, name='pesquisar_usuario'),
    url(r'^obter_campos_usuario$', viewUsuario.obter_campos_usuario, name='obter_campos_usuario'),
    url(r'^verificar_senha_atual$', viewUsuario.verificar_senha_atual, name='verificar_senha_atual'),
    url(r'^tela_cadastro_ok$', viewUsuario.tela_cadastro_ok, name='tela_cadastro_ok'),
    url(r'^tela_cadastro_erro$', viewUsuario.tela_cadastro_erro, name='tela_cadastro_erro'),
    # Tipos de Usuário
    url(r'^tipo_usuario$', viewTipoUsuario.tipo_usuario, name='tipo_usuario'),
    url(r'^novo_tipo_usuario$', viewTipoUsuario.novo_tipo_usuario, name='novo_tipo_usuario'),
    url(r'^inativar_tipo_usuario$', viewTipoUsuario.inativar_tipo_usuario, name='inativar_tipo_usuario'),
    #url(r'^obter_relatorio_tipo_usuario$', viewTipoUsuario.obter_relatorio_tipo_usuario, 
    #   name='obter_relatorio_tipo_usuario'),
    url(r'^cadastrar_tipo_usuario$', viewTipoUsuario.cadastrar_tipo_usuario, name='cadastrar_tipo_usuario'),
    url(r'^verificarPerfil$', viewTipoUsuario.verificarPerfil, name='verificarPerfil'),
    url(r'^pesquisar_tipo_usuario$', viewTipoUsuario.pesquisar_tipo_usuario, name='pesquisar_tipo_usuario'),
    url(r'^obter_campos_tipo_usuario$', viewTipoUsuario.obter_campos_tipo_usuario, 
        name='obter_campos_tipo_usuario'),
    # Tipos de Usuário Administrativo
    url(r'^tipo_usuario_administrativo$', viewTipoUsuarioAdministrativo.tipo_usuario_administrativo, 
        name='tipo_usuario_administrativo'),
    url(r'^novo_tipo_usuario_administrativo$', viewTipoUsuarioAdministrativo.novo_tipo_usuario_administrativo, 
        name='novo_tipo_usuario_administrativo'),
    url(r'^inativar_tipo_usuario_administrativo$', 
        viewTipoUsuarioAdministrativo.inativar_tipo_usuario_administrativo,
        name='inativar_tipo_usuario_administrativo'),
    url(r'^cadastrar_tipo_usuario_administrativo$', 
        viewTipoUsuarioAdministrativo.cadastrar_tipo_usuario_administrativo, 
        name='cadastrar_tipo_usuario_administrativo'),
    url(r'^pesquisar_tipo_usuario_administrativo$', 
        viewTipoUsuarioAdministrativo.pesquisar_tipo_usuario_administrativo, 
        name='pesquisar_tipo_usuario_administrativo'),
    url(r'^obter_campos_tipo_usuario_administrativo$', 
        viewTipoUsuarioAdministrativo.obter_campos_tipo_usuario_administrativo, 
        name='obter_campos_tipo_usuario_administrativo'),
    url(r'^verifica_nome_tipo_usuario$', viewTipoUsuarioAdministrativo.verifica_nome_tipo_usuario, 
        name='verifica_nome_tipo_usuario'),
    # Opcional
    url(r'^opcional$', viewOpcionais.opcional, name='opcional'),
    url(r'^novo_opcional$', viewOpcionais.novo_opcional, name='novo_opcional'),
    url(r'^cadastrar_opcional$', viewOpcionais.cadastrar_opcional, name='cadastrar_opcional'),
    url(r'^inativar_opcionais$', viewOpcionais.inativar_opcionais, name='inativar_opcionais'),
    url(r'^pesquisar_opcional$', viewOpcionais.pesquisar_opcional, name='pesquisar_opcional'),
    url(r'^obter_campos_opcional$', viewOpcionais.obter_campos_opcional, name='obter_campos_opcional'),
    url(r'^consultar_opcional$', viewOpcionais.consultar_opcional, name='consultar_opcional'),
    # Nota fiscal entrada
    url(r'^notafiscal_entrada$', viewNotaFiscalEntrada.notafiscal_entrada, name='notafiscal_entrada'),
    url(r'^novo_notafiscal_entrada$', viewNotaFiscalEntrada.novo_notafiscal_entrada, 
        name='novo_notafiscal_entrada'),
    url(r'^obterValorUnitario$', viewNotaFiscalEntrada.obterValorUnitario, name='obterValorUnitario'),
    url(r'^cadastrar_notafiscal_entrada$', viewNotaFiscalEntrada.cadastrar_notafiscal_entrada, 
        name='cadastrar_notafiscal_entrada'),
    url(r'^inativar_notafiscal_entrada$', viewNotaFiscalEntrada.inativar_notafiscal_entrada, 
        name='inativar_notafiscal_entrada'),
    #url(r'^validarNumNF$', viewNotaFiscalEntrada.validarNumNF, name='validarNumNF'),
    url(r'^pesquisar_notafiscal_entrada$', viewNotaFiscalEntrada.pesquisar_notafiscal_entrada, 
        name='pesquisar_notafiscal_entrada'),
    url(r'^obter_campos_notafiscal_entrada$', viewNotaFiscalEntrada.obter_campos_notafiscal_entrada, 
        name='obter_campos_notafiscal_entrada'),
    url(r'^consultar_serie_numero_nf$', viewNotaFiscalEntrada.consultar_serie_numero_nf, 
        name='consultar_serie_numero_nf'),
    # Nota Fiscal de Saída
    url(r'^notafiscal_saida$', viewNotaFiscalSaida.notafiscal_saida, name='notafiscal_saida'),
    url(r'^notafiscal_saida_nfce$', viewNotaFiscalSaida.notafiscal_saida_nfce, name='notafiscal_saida_nfce'),
    url(r'^novo_notafiscal_saida$', viewNotaFiscalSaida.novo_notafiscal_saida, name='novo_notafiscal_saida'),
    url(r'^novo_notafiscal_saida_nfce$', viewNotaFiscalSaida.novo_notafiscal_saida_nfce, 
        name='novo_notafiscal_saida_nfce'),
    url(r'^obter_sequencia_serie$', viewNotaFiscalSaida.obter_sequencia_serie, name='obter_sequencia_serie'),
    url(r'^obterValorUnitario$', viewNotaFiscalSaida.obterValorUnitario, name='obterValorUnitario'),
    url(r'^salvar_pedido$', viewNotaFiscalSaida.salvar_pedido, name='salvar_pedido'),
    url(r'^salvar_pedido_transmitir$', viewNotaFiscalSaida.salvar_pedido_transmitir, 
        name='salvar_pedido_transmitir'),
    url(r'^consultar_webservices_receita$', viewNotaFiscalSaida.consultar_webservices_receita, 
        name='consultar_webservices_receita'),
    url(r'^cancelar_notafiscal_saida$', viewNotaFiscalSaida.cancelar_notafiscal_saida, 
        name='cancelar_notafiscal_saida'),
    url(r'^consultar_status_nfe$', viewNotaFiscalSaida.consultar_status_nfe, name='consultar_status_nfe'),
    #url(r'^inativar_notafiscal_saida$', viewNotaFiscalSaida.inativar_notafiscal_saida, 
    #    name='inativar_notafiscal_saida'),
    url(r'^inutilizar_numeracao$', viewNotaFiscalSaida.inutilizar_numeracao, name='inutilizar_numeracao'),
    url(r'^enviar_notafiscal_email$', viewNotaFiscalSaida.enviar_notafiscal_email, 
        name='enviar_notafiscal_email'),
    url(r'^obter_danfe_pdf$', viewNotaFiscalSaida.obter_danfe_pdf, name='obter_danfe_pdf'),
    url(r'^pesquisar_notafiscal_saida$', viewNotaFiscalSaida.pesquisar_notafiscal_saida, 
        name='pesquisar_notafiscal_saida'),
    url(r'^obter_campos_notafiscal_saida$', viewNotaFiscalSaida.obter_campos_notafiscal_saida, 
        name='obter_campos_notafiscal_saida'),
    url(r'^imprimir_pedido$', viewNotaFiscalSaida.imprimir_pedido, name='imprimir_pedido'),
    url(r'^gerenciar_loja_virtual$', viewNotaFiscalSaida.gerenciar_loja_virtual, 
        name='gerenciar_loja_virtual'),
    url(r'^filtar_nf_gerenciar_loja_virtual$', 
        viewNotaFiscalSaida.filtar_nf_gerenciar_loja_virtual, 
        name='filtar_nf_gerenciar_loja_virtual'),
    url(r'^salvar_qtde_impressos$', 
        viewNotaFiscalSaida.salvar_qtde_impressos, name='salvar_qtde_impressos'),
    # Vendas
    url(r'^venda$', viewNotaFiscalSaida.venda, name='venda'),
    url(r'^nova_venda$', viewNotaFiscalSaida.nova_venda, name='nova_venda'),
    url(r'^cadastrar_venda$', viewNotaFiscalSaida.cadastrar_venda, name='cadastrar_venda'),
    url(r'^pesquisar_venda$', viewNotaFiscalSaida.pesquisar_venda, name='pesquisar_venda'),
    url(r'^obter_campos_venda$', viewNotaFiscalSaida.obter_campos_venda, name='obter_campos_venda'),
    url(r'^imprimir_venda$', viewNotaFiscalSaida.imprimir_venda, name='imprimir_venda'),
    url(r'^enviar_venda_email$', viewNotaFiscalSaida.enviar_venda_email, name='enviar_venda_email'),
    #url(r'^inativar_venda$', viewNotaFiscalSaida.inativar_venda, name='inativar_venda'),
    url(r'^alterar_encerramento$', viewNotaFiscalSaida.alterar_encerramento, name='alterar_encerramento'),
    # NF-e de devolução
    url(r'^devolucao_notafiscal$', viewNotaFiscalSaida.devolucao_notafiscal, name='devolucao_notafiscal'),
    # Notas fiscais de saída canceladas
    url(r'^notafiscal_saida_cancelada$', viewNotaFiscalSaida.notafiscal_saida_cancelada, 
        name='notafiscal_saida_cancelada'),
    url(r'^notafiscal_saida_cancelada_nfce$', viewNotaFiscalSaida.notafiscal_saida_cancelada_nfce, 
        name='notafiscal_saida_cancelada_nfce'),
    # Numerações inutilizadas
    url(r'^numeracao_inutilizada$', viewNotaFiscalSaida.numeracao_inutilizada, name='numeracao_inutilizada'),
    # Relatórios nota fiscal de entrada e saída
    url(r'^relatorio_notafiscal_entrada_saida$', 
        viewRelatorioNotaFiscalEntradaSaida.relatorio_notafiscal_entrada_saida, 
        name='relatorio_notafiscal_entrada_saida'),
    url(r'^relatorio_notafiscal_entrada_saida_nfce$', 
        viewRelatorioNotaFiscalEntradaSaida.relatorio_notafiscal_entrada_saida_nfce, 
        name='relatorio_notafiscal_entrada_saida_nfce'),
    url(r'^filtrar_relatorio_nota_fiscal$', 
        viewRelatorioNotaFiscalEntradaSaida.filtrar_relatorio_nota_fiscal, 
        name='filtrar_relatorio_nota_fiscal'),
    url(r'^filtrar_relatorio_nota_fiscal_pdf$', 
        viewRelatorioNotaFiscalEntradaSaida.filtrar_relatorio_nota_fiscal_pdf, 
        name='filtrar_relatorio_nota_fiscal_pdf'),
    # Email de NF-e por período
    url(r'^email_nfe_periodo$', viewNotaFiscalSaida.email_nfe_periodo, name='email_nfe_periodo'),
    url(r'^enviar_email_nfe_periodo$', viewNotaFiscalSaida.enviar_email_nfe_periodo, 
        name='enviar_email_nfe_periodo'),
    url(r'^consultar_cnpj_receita$', viewEmpresa.consultar_cnpj_receita, name='consultar_cnpj_receita'),
    url(r'^recarregar_captcha_receita$', viewEmpresa.recarregar_captcha_receita, 
        name='recarregar_captcha_receita'),
    url(r'^consultar_dados_nfe$', viewNotaFiscalSaida.consultar_dados_nfe, name='consultar_dados_nfe'),
    url(r'^consultar_nfe_receita$', viewNotaFiscalSaida.consultar_nfe_receita, name='consultar_nfe_receita'),
    url(r'^recarregar_captcha_consulta_nfe$', viewNotaFiscalSaida.recarregar_captcha_consulta_nfe, 
        name='recarregar_captcha_consulta_nfe'),
    # Vendas
    url(r'^consulta_vendas$', viewConsultaVendas.consulta_vendas, name='consulta_vendas'),
    url(r'^obter_dados_vendas$', viewConsultaVendas.obter_dados_vendas, name='obter_dados_vendas'),
    # Pedidos
    url(r'^encerramento_pedido$', viewNotaFiscalSaida.encerramento_pedido, name='encerramento_pedido'),
    url(r'^encerrar_pedido$', viewNotaFiscalSaida.encerrar_pedido, name='encerrar_pedido'),
    url(r'^pedidos_encerrados$', viewNotaFiscalSaida.pedidos_encerrados, name='pedidos_encerrados'),
    # Parâmetros
    url(r'^parametro$', viewParametro.parametro, name='parametro'),
    url(r'^novo_parametro$', viewParametro.novo_parametro, name='novo_parametro'),
    url(r'^cadastrar_parametro$', viewParametro.cadastrar_parametro, name='cadastrar_parametro'),
    url(r'^pesquisar_parametro$', viewParametro.pesquisar_parametro, name='pesquisar_parametro'),
    url(r'^obter_campos_parametro$', viewParametro.obter_campos_parametro, name='obter_campos_parametro'),
    url(r'^inativar_parametro$', viewParametro.inativar_parametro, name='cadastrar_parametro'),
    # Ocorrências
    url(r'^ocorrencia$', viewOcorrencia.ocorrencia, name='ocorrencia'),
    url(r'^nova_ocorrencia$', viewOcorrencia.nova_ocorrencia, name='nova_ocorrencia'),
    url(r'^cadastrar_ocorrencia$', viewOcorrencia.cadastrar_ocorrencia, name='cadastrar_ocorrencia'),
    url(r'^pesquisar_ocorrencia$', viewOcorrencia.pesquisar_ocorrencia, name='pesquisar_ocorrencia'),
    url(r'^obter_campos_ocorrencia$', viewOcorrencia.obter_campos_ocorrencia, name='obter_campos_ocorrencia'),
    #url(r'^ocorrencias_administrativo$', viewOcorrencia.ocorrencias_administrativo, 
    #    name='ocorrencias_administrativo'),
    #url(r'^ocorrencias_resolvidas$', viewOcorrencia.ocorrencias_resolvidas, name='ocorrencias_resolvidas'),
    # Atendente
    url(r'^atendente$', viewAtendente.atendente, name='atendente'),
    url(r'^novo_atendente$', viewAtendente.novo_atendente, name='novo_atendente'),
    url(r'^cadastrar_atendente$', viewAtendente.cadastrar_atendente, name='cadastrar_atendente'),
    #url(r'^mostrar_atendentes$', viewAtendente.mostrar_atendentes, name='mostrar_atendentes'),
    url(r'^inativar_atendentes$', viewAtendente.inativar_atendentes, name='inativar_atendentes'),
    url(r'^pesquisar_atendente$', viewAtendente.pesquisar_atendente, name='pesquisar_atendente'),
    url(r'^obter_campos_atendente$', viewAtendente.obter_campos_atendente, name='obter_campos_atendente'),
    # Contato ocorrências
    url(r'^contato$', viewContato.contato, name='contato'),
    url(r'^novo_contato$', viewContato.novo_contato, name='novo_contato'),
    url(r'^cadastrar_contato$', viewContato.cadastrar_contato, name='cadastrar_contato'),
    url(r'^inativar_contatos$', viewContato.inativar_contatos, name='inativar_contatos'),
    url(r'^pesquisar_contato$', viewContato.pesquisar_contato, name='pesquisar_contato'),
    url(r'^obter_campos_contato$', viewContato.obter_campos_contato, name='obter_campos_contato'),
    # Tipo de documento
    url(r'^tipo_documento$', viewTipoDocumento.tipo_documento, name='tipo_documento'),
    url(r'^novo_tipo_documento$', viewTipoDocumento.novo_tipo_documento, name='novo_tipo_documento'),
    url(r'^cadastrar_tipo_documento$', viewTipoDocumento.cadastrar_tipo_documento, 
        name='cadastrar_tipo_documento'),
    url(r'^inativar_tipos_documento$', viewTipoDocumento.inativar_tipos_documento, 
        name='inativar_tipos_documento'),
    url(r'^pesquisar_tipo_documento$', viewTipoDocumento.pesquisar_tipo_documento, 
        name='pesquisar_tipo_documento'),
    url(r'^obter_campos_tipo_documento$', viewTipoDocumento.obter_campos_tipo_documento, 
        name='obter_campos_tipo_documento'),
    # Transação
    url(r'^transacao$', viewTransacao.transacao, name='transacao'),
    url(r'^nova_transacao$', viewTransacao.nova_transacao, name='nova_transacao'),
    url(r'^cadastrar_transacao$', viewTransacao.cadastrar_transacao, name='cadastrar_transacao'),
    url(r'^inativar_transacoes$', viewTransacao.inativar_transacoes, name='inativar_transacoes'),
    url(r'^pesquisar_transacao$', viewTransacao.pesquisar_transacao, name='pesquisar_transacao'),
    url(r'^obter_campos_transacao$', viewTransacao.obter_campos_transacao, name='obter_campos_transacao'),
    url(r'^consultar_transacao$', viewTransacao.consultar_transacao, name='consultar_transacao'),
    url(r'^consultar_transacao_padrao$', viewTransacao.consultar_transacao_padrao, 
        name='consultar_transacao_padrao'),
    url(r'^consultar_nome_transacao$', viewTransacao.consultar_nome_transacao, 
        name='consultar_nome_transacao'),
    # Conta Bancária
    url(r'^conta_bancaria$', viewContaBancaria.conta_bancaria, name='conta_bancaria'),
    url(r'^nova_conta_bancaria$', viewContaBancaria.nova_conta_bancaria, name='nova_conta_bancaria'),
    url(r'^cadastrar_conta_bancaria$', viewContaBancaria.cadastrar_conta_bancaria, 
        name='cadastrar_conta_bancaria'),
    url(r'^inativar_contas_bancarias$', viewContaBancaria.inativar_contas_bancarias, 
        name='inativar_contas_bancarias'),
    url(r'^pesquisar_conta_bancaria$', viewContaBancaria.pesquisar_conta_bancaria, 
        name='pesquisar_conta_bancaria'),
    url(r'^obter_campos_conta_bancaria$', viewContaBancaria.obter_campos_conta_bancaria, 
        name='obter_campos_conta_bancaria'),
    url(r'^consultar_conta$', viewContaBancaria.consultar_conta, name='consultar_conta'),
    url(r'^consultar_conta_bancaria$', viewContaBancaria.consultar_conta_bancaria, 
        name='consultar_conta_bancaria'),
    url(r'^consultar_conta_padrao$', viewContaBancaria.consultar_conta_padrao, name='consultar_conta_padrao'),
    # Carteira Bancária
    url(r'^carteira_bancaria$', viewCarteiraBancaria.carteira_bancaria, name='carteira_bancaria'),
    url(r'^nova_carteira_bancaria$', viewCarteiraBancaria.nova_carteira_bancaria, 
        name='nova_carteira_bancaria'),
    url(r'^cadastrar_carteira_bancaria$', viewCarteiraBancaria.cadastrar_carteira_bancaria, 
        name='cadastrar_carteira_bancaria'),
    url(r'^inativar_carteiras_bancarias$', viewCarteiraBancaria.inativar_carteiras_bancarias, 
        name='inativar_carteiras_bancarias'),
    url(r'^pesquisar_carteira_bancaria$', viewCarteiraBancaria.pesquisar_carteira_bancaria, 
        name='pesquisar_carteira_bancaria'),
    url(r'^obter_campos_carteira_bancaria$', viewCarteiraBancaria.obter_campos_carteira_bancaria, 
        name='obter_campos_carteira_bancaria'),
    # Depósito
    url(r'^deposito$', viewDeposito.deposito, name='deposito'),
    url(r'^novo_deposito$', viewDeposito.novo_deposito, name='novo_deposito'),
    url(r'^cadastrar_deposito$', viewDeposito.cadastrar_deposito, name='cadastrar_deposito'),
    url(r'^inativar_depositos$', viewDeposito.inativar_depositos, name='inativar_depositos'),
    url(r'^pesquisar_deposito$', viewDeposito.pesquisar_deposito, name='pesquisar_deposito'),
    url(r'^obter_campos_deposito$', viewDeposito.obter_campos_deposito, name='obter_campos_deposito'),
    # Relatórios
    url(r'^relatorio_contas_pagar$', viewRelatorioContas.contas_pagar, name='contas_pagar'),
    url(r'^relatorio_contas_receber$', viewRelatorioContas.contas_receber, name='contas_receber'),
    url(r'^relatorio_contas_pagar_vencer$', viewRelatorioContas.contas_pagar_vencer, 
        name='contas_pagar_vencer'),
    url(r'^relatorio_contas_receber_vencer$', viewRelatorioContas.contas_receber_vencer, 
        name='contas_receber_vencer'),
    url(r'^relatorio_contas_receber_pagar$', viewRelatorioContas.relatorio_contas_receber_pagar, 
        name='relatorio_contas_receber_pagar'),
    url(r'^get_data_bismart$', viewRelatorioContas.get_data_bismart, name='get_data_bismart'),
    url(r'^get_data_bismart.+$', viewRelatorioContas.get_data_bismart, name='get_data_bismart'),
    url(r'^get_data_produto_bismart$', viewRelatorioContas.get_data_produto_bismart, 
        name='get_data_produto_bismart'),
    url(r'^get_data_produto_bismart.+$', viewRelatorioContas.get_data_produto_bismart, 
        name='get_data_produto_bismart'),
    url(r'^get_data_cliente_bismart$', viewRelatorioContas.get_data_cliente_bismart, 
        name='get_data_cliente_bismart'),
    url(r'^get_data_cliente_bismart.+$', viewRelatorioContas.get_data_cliente_bismart, 
        name='get_data_cliente_bismart'),
    url(r'^grafico_contas_recebidas_pagas$', viewRelatorioContas.grafico_contas_recebidas_pagas,
        name='grafico_contas_recebidas_pagas'),
    url(r'^relatorio_contas_recebidas_pagas$', viewRelatorioContas.relatorio_contas_recebidas_pagas,
        name='relatorio_contas_recebidas_pagas'),
    url(r'^calendario_financeiro_realizar$', viewRelatorioContas.calendario_financeiro_realizar, 
        name='calendario_financeiro_realizar'),
    # Finanças
    url(r'^financa$', viewFinanca.financa, name='financa'),
    url(r'^nova_financa$', viewFinanca.nova_financa, name='nova_financa'),
    url(r'^cadastrar_financa$', viewFinanca.cadastrar_financa, name='cadastrar_financa'),
    url(r'^inativar_financa$', viewFinanca.inativar_financa, name='inativar_financa'),
    url(r'^recebimento_financa$', viewFinanca.recebimento_financa, name='recebimento_financa'),
    url(r'^pagamento_financa$', viewFinanca.recebimento_financa, name='recebimento_financa'),
    url(r'^estorno_recebimento$', viewFinanca.estorno_financa, name='estorno_financa'),
    url(r'^estorno_pagamento$', viewFinanca.estorno_financa, name='estorno_financa'),
    url(r'^efetuar_estorno_financa$',viewFinanca.efetuar_estorno_financa, 
        name='efetuar_estorno_financa'),
    url(r'^recebimento_titulos_filtrados$', viewFinanca.recebimento_titulos_filtrados, 
        name='recebimento_titulos_filtrados'),
    url(r'^obter_contas_bancarias$', viewFinanca.obter_contas_bancarias, name='obter_contas_bancarias'),
    url(r'^obter_transacoes$', viewFinanca.obter_transacoes, name='obter_transacoes'),
    url(r'^verificar_documento$', viewFinanca.verificar_documento, name='verificar_documento'),
    url(r'^gerar_codigo_documento$', viewFinanca.gerar_codigo_documento, name='gerar_codigo_documento'),
    url(r'^obter_campos_financa$', viewFinanca.obter_campos_financa, name='obter_campos_financa'),
    url(r'^pesquisar_financa$', viewFinanca.pesquisar_financa, name='pesquisar_financa'),
    url(r'^efetuar_recebimento_titulos$', viewFinanca.efetuar_recebimento_titulos, 
        name='efetuar_recebimento_titulos'),
    url(r'^validar_doc_recebimento$',viewFinanca.validar_doc_recebimento, name='validar_doc_recebimento'),
    url(r'^filtrar_relatorio_financas$',viewRelatorioContas.filtrar_relatorio_financas, 
        name='filtrar_relatorio_financas'),
    url(r'^filtrar_relatorio_contas_recebidas_pagas$',viewRelatorioContas.filtrar_relatorio_contas_recebidas_pagas,
        name='filtrar_relatorio_contas_recebidas_pagas'),
    url(r'^filtrar_dados_calendario_financeiro$',viewRelatorioContas.filtrar_dados_calendario_financeiro,
        name='filtrar_dados_calendario_financeiro'),
    url(r'^filtrar_relatorio_calendario_financeiro$',viewRelatorioContas.filtrar_relatorio_calendario_financeiro,
        name='filtrar_relatorio_calendario_financeiro'),
    # Classificação fiscal (NCM)
    url(r'^classificacao_fiscal$', viewClassificacaoFiscal.classificacao_fiscal, name='classificacao_fiscal'),
    url(r'^nova_classificacao_fiscal$', viewClassificacaoFiscal.nova_classificacao_fiscal, 
        name='nova_classificacao_fiscal'),
    url(r'^cadastrar_classificacao_fiscal$', viewClassificacaoFiscal.cadastrar_classificacao_fiscal, 
        name='cadastrar_classificacao_fiscal'),
    url(r'^inativar_classificacoes_fiscais$', viewClassificacaoFiscal.inativar_classificacoes_fiscais, 
        name='inativar_classificacoes_fiscais'),
    url(r'^pesquisar_classificacao_fiscal$', viewClassificacaoFiscal.pesquisar_classificacao_fiscal, 
        name='pesquisar_classificacao_fiscal'),
    url(r'^obter_campos_classificacao_fiscal$', viewClassificacaoFiscal.obter_campos_classificacao_fiscal, 
        name='obter_campos_classificacao_fiscal'),
    url(r'^importar_arquivo_ibpt$', viewClassificacaoFiscal.importar_arquivo_ibpt, 
        name="importar_arquivo_ibpt"),
    url(r'^resgata_ncms$', viewClassificacaoFiscal.resgata_ncms, name='resgata_ncms'),
    url(r'^obter_ncms$', viewClassificacaoFiscal.obter_ncms, name='obter_ncms'),
    # Classificação fiscal (NCM) administrativo
    url(r'^classificacao_fiscal_administrativo$', viewClassificacaoFiscal.classificacao_fiscal_administrativo, 
        name='classificacao_fiscal_administrativo'),
    url(r'^nova_classificacao_fiscal_administrativo$', 
        viewClassificacaoFiscal.nova_classificacao_fiscal_administrativo, 
        name='nova_classificacao_fiscal_administrativo'),
    # Natureza de Operação (CFOP)
    url(r'^natureza_operacao$', viewNaturezaOperacao.natureza_operacao, name='natureza_operacao'),
    url(r'^nova_natureza_operacao$', viewNaturezaOperacao.nova_natureza_operacao, 
        name='nova_natureza_operacao'),
    url(r'^cadastrar_natureza_operacao$', viewNaturezaOperacao.cadastrar_natureza_operacao, 
        name='cadastrar_natureza_operacao'),
    #url(r'^mostrar_natureza_operacoes$', viewNaturezaOperacao.mostrar_natureza_operacoes, 
    #   name='mostrar_natureza_operacoes'),
    url(r'^inativar_natureza_operacoes$', viewNaturezaOperacao.inativar_natureza_operacoes, 
        name='inativar_natureza_operacoes'),
    url(r'^obter_campos_natureza_operacao$', viewNaturezaOperacao.obter_campos_natureza_operacao, 
        name='obter_campos_natureza_operacao'),
    url(r'^pesquisar_natureza_operacao$', viewNaturezaOperacao.pesquisar_natureza_operacao, 
        name='pesquisar_natureza_operacao'),
    url(r'^consultar_natureza_operacao$', viewNaturezaOperacao.consultar_natureza_operacao, 
        name='consultar_natureza_operacao'),
    # Funções
    url(r'^lista_cidades$', funcoes.get_lista_cidades, name='get_lista_cidades'),
    url(r'^lista_estados$', funcoes.get_lista_estados, name='get_lista_estado'),
    url(r'^imagens/add$', viewGerenciadorImagens.add, name='viewGerenciadorImagens'),
    url(r'^exportador_sql/export_sql_file$', viewExportadorSql.export_sql_file, name='export_sql_file'),
    # Séries
    url(r'^serie$', viewSerie.serie, name='serie'),
    url(r'^nova_serie$', viewSerie.nova_serie, name='nova_serie'),
    #url(r'^mostrar_series$', viewSerie.mostrar_series, name='mostrar_series'),
    url(r'^inativar_series$', viewSerie.inativar_series, name='inativar_series'),
    url(r'^cadastrar_serie$', viewSerie.cadastrar_serie, name='cadastrar_serie'),
    url(r'^pesquisar_serie$', viewSerie.pesquisar_serie, name='pesquisar_serie'),
    url(r'^obter_campos_serie$', viewSerie.obter_campos_serie, name='obter_campos_serie'),
    # Atributo
    url(r'^atributo$', viewAtributo.atributo, name='atributo'),
    url(r'^novo_atributo$', viewAtributo.novo_atributo, name='novo_atributo'),
    url(r'^cadastrar_atributo$', viewAtributo.cadastrar_atributo, name='cadastrar_atributo'),
    url(r'^obter_atributos_produto$', viewAtributo.obter_atributos_produto, name='obter_atributos_produto'),
    url(r'^inativar_atributos$', viewAtributo.inativar_atributos, name='inativar_atributos'),
    url(r'^pesquisar_atributo$', viewAtributo.pesquisar_atributo, name='pesquisar_atributo'),
    url(r'^obter_campos_atributo$', viewAtributo.obter_campos_atributo, name='obter_campos_atributo'),
    # Representante
    url(r'^representante$', viewRepresentante.representante, name='representante'),
    url(r'^novo_representante$', viewRepresentante.novo_representante, name='novo_representante'),
    url(r'^cadastrar_representante$', viewRepresentante.cadastrar_representante, 
        name='cadastrar_representante'),
    #url(r'^mostrar_representantes$', viewRepresentante.mostrar_representantes, name='mostrar_representantes'),
    url(r'^obter_representantes_cliente$', viewRepresentante.obter_representantes_cliente, 
        name='obter_representantes_cliente'),
    url(r'^inativar_representantes$', viewRepresentante.inativar_representantes, 
        name='inativar_representantes'),
    url(r'^obter_id_representante$', viewRepresentante.obter_id_representante, 
        name='obter_id_representante'),
    url(r'^pesquisar_representante$', viewRepresentante.pesquisar_representante, 
        name='pesquisar_representante'),
    url(r'^obter_campos_representante$', viewRepresentante.obter_campos_representante, 
        name='obter_campos_representante'),
    # condicao de pagamento
    url(r'^condicao_pagamento$', viewCondicaoPagamento.condicao_pagamento, name='condicao_pagamento'),
    url(r'^nova_condicao_pagamento$', viewCondicaoPagamento.nova_condicao_pagamento, 
        name='nova_condicao_pagamento'),
    url(r'^cadastrar_condicao_pagamento$', viewCondicaoPagamento.cadastrar_condicao_pagamento, 
        name='cadastrar_condicao_pagamento'),
    #url(r'^mostrar_condicoes_pagamento$', viewCondicaoPagamento.mostrar_condicoes_pagamento, 
    #   name='mostrar_condicoes_pagamento'),
    url(r'^inativar_condicao_pagamento$', viewCondicaoPagamento.inativar_condicao_pagamento, 
        name='inativar_condicao_pagamento'),
    url(r'^pesquisar_condicao_pagamento$', viewCondicaoPagamento.pesquisar_condicao_pagamento, 
        name='pesquisar_condicao_pagamento'),
    url(r'^obter_campos_condicao_pagamento$',viewCondicaoPagamento.obter_campos_condicao_pagamento, 
        name='obter_campos_condicao_pagamento'),
    # Parte Administrativa
    url(r'^home_administrativo$', viewHomeAdministrativo.home_administrativo, name='home_administrativo'),
    url(r'^empresa_administrativo$', viewEmpresaAdministrativo.empresa_administrativo, 
        name='empresa_administrativo'),
    url(r'^trocar_empresa$', viewEmpresaAdministrativo.trocar_empresa, name='trocar_empresa'),
    url(r'^pesquisar_empresa_administrativo$', viewEmpresaAdministrativo.pesquisar_empresa_administrativo, 
        name='pesquisar_empresa_administrativo'),
    url(r'^relatorio_cliente_administrativo$', viewRelatoriosAdministrativo.relatorio_cliente_administrativo, 
        name='relatorio_cliente_administrativo'),
    url(r'^relatorio_produto_administrativo$', viewRelatoriosAdministrativo.relatorio_produto_administrativo, 
        name='relatorio_produto_administrativo'),
    url(r'^relatorio_usuario_administrativo$', viewRelatoriosAdministrativo.relatorio_usuario_administrativo, 
        name='relatorio_usuario_administrativo'),
    url(r'^relatorio_pedido_administrativo$', viewRelatoriosAdministrativo.relatorio_pedido_administrativo, 
        name='relatorio_pedido_administrativo'),
    url(r'^relatorio_notafiscal_entrada_administrativo$', 
        viewRelatoriosAdministrativo.relatorio_notafiscal_entrada_administrativo, 
        name='relatorio_notafiscal_entrada_administrativo'),
    url(r'^relatorio_notafiscal_saida_administrativo$', 
        viewRelatoriosAdministrativo.relatorio_notafiscal_saida_administrativo, 
        name='relatorio_notafiscal_saida_administrativo'),
    url(r'^obter_campos_empresa_administrativo$', 
        viewEmpresaAdministrativo.obter_campos_empresa_administrativo, 
        name='obter_campos_empresa_administrativo'),
    url(r'^excluir_empresa$', viewEmpresaAdministrativo.excluir_empresa, name='excluir_empresa'),
    url(r'^restaurar_empresa$', viewEmpresaAdministrativo.restaurar_empresa, name='restaurar_empresa'),
    # Status
    url(r'^status$', viewStatus.status, name='status'),
    url(r'^verificarStatus$', viewStatus.verificarStatus, name='verificarStatus'),
    # Console
    url(r'^console$', viewConsole.console, name='console'),
    url(r'^executar_sql$', viewConsole.executar_sql, name='executar_sql'),
    #url(r'^analizarSql$', viewConsole.analizarSql, name='analizarSql'),
    # Financeira
    url(r'^financeira$', viewFinanceira.financeira, name='financeira'),
    url(r'^nova_financeira$', viewFinanceira.nova_financeira, name='nova_financeira'),
    url(r'^cadastrar_financeira$', viewFinanceira.cadastrar_financeira, name='cadastrar_financeira'),
    url(r'^inativar_financeira$', viewFinanceira.inativar_financeira, name='inativar_financeira'),
    url(r'^pesquisar_financeira$', viewFinanceira.pesquisar_financeira, name='pesquisar_financeira'),
    url(r'^obter_campos_financeira$', viewFinanceira.obter_campos_financeira, name='obter_campos_financeira'),
    # Banco
    url(r'^banco$', viewBanco.banco, name='banco'),
    url(r'^novo_banco$', viewBanco.novo_banco, name='novo_banco'),
    url(r'^cadastrar_banco$', viewBanco.cadastrar_banco, name='cadastrar_banco'),
    url(r'^inativar_banco$', viewBanco.inativar_banco, name='inativar_banco'),
    url(r'^pesquisar_banco$', viewBanco.pesquisar_banco, name='pesquisar_banco'),
    url(r'^obter_campos_banco$',viewBanco.obter_campos_banco, name='obter_campos_banco'),
    url(r'^consultar_cod_compensacao$',viewBanco.consultar_cod_compensacao, name='consultar_cod_compensacao'),
    url(r'^banco_administrativo$', viewBanco.banco_administrativo, name='banco_administrativo'),
    url(r'^novo_banco_administrativo$', viewBanco.novo_banco_administrativo, name='novo_banco_administrativo'),
    url(r'^inativar_banco_administrativo$', viewBanco.inativar_banco_administrativo, 
        name='inativar_banco_administrativo'),
    url(r'^pesquisar_banco_administrativo$', viewBanco.pesquisar_banco_administrativo, 
        name='pesquisar_banco_administrativo'),
    url(r'^obter_campos_banco_administrativo$',viewBanco.obter_campos_banco_administrativo, 
        name='obter_campos_banco_administrativo'),
    url(r'^consultar_cod_compensacao_administrativo$',viewBanco.consultar_cod_compensacao_administrativo, 
        name='consultar_cod_compensacao_administrativo'),
    # Movimentacao de Contas receber e pagar
    url(r'^movimentacao_contas$', viewMovimentacaoContas.movimentacao_contas, name='movimentacao_contas'),
    url(r'^nova_movimentacao_contas$', viewMovimentacaoContas.nova_movimentacao_contas, 
        name='nova_movimentacao_contas'),
    url(r'^cadastrar_movimentacao_contas$', viewMovimentacaoContas.cadastrar_movimentacao_contas, 
        name='cadastrar_movimentacao_contas'),
    url(r'^excluir_movimentacao_contas$', viewMovimentacaoContas.excluir_movimentacao_contas, 
        name='excluir_movimentacao_contas'),
    url(r'^pesquisar_movimentacao_contas$', viewMovimentacaoContas.pesquisar_movimentacao_contas, 
        name='pesquisar_movimentacao_contas'),
    url(r'^obter_campos_movimentacao_contas$', viewMovimentacaoContas.obter_campos_movimentacao_contas, 
        name='obter_campos_movimentacao_contas'),
    url(r'^relatorio_movimentacao_contas$', viewMovimentacaoContas.relatorio_movimentacao_contas, 
        name='relatorio_movimentacao_contas'),
    url(r'^filtrar_relatorio_movimentacao_contas$', 
        viewMovimentacaoContas.filtrar_relatorio_movimentacao_contas, 
        name='filtrar_relatorio_movimentacao_contas'),
    url(r'^gerar_codigo_documento_movimentacao$', viewMovimentacaoContas.gerar_codigo_documento_movimentacao, 
        name='gerar_codigo_documento_movimentacao'),
    url(r'^obter_dados_movimentacao$', viewMovimentacaoContas.obter_dados_movimentacao, 
        name='obter_dados_movimentacao'),
    # Carteira Boleta
    url(r'^configuracao_boleto$', viewConfiguracaoBoleto.configuracao_boleto, name='configuracao_boleto'),
    url(r'^nova_configuracao_boleto$', viewConfiguracaoBoleto.nova_configuracao_boleto, 
        name='nova_configuracao_boleto'),
    url(r'^cadastrar_configuracao_boleto$', viewConfiguracaoBoleto.cadastrar_configuracao_boleto, 
        name='cadastrar_configuracao_boleto'),
    url(r'^inativar_configuracao_boleto$', viewConfiguracaoBoleto.inativar_configuracao_boleto, 
        name='inativar_configuracao_boleto'),
    url(r'^pesquisar_configuracao_boleto$', viewConfiguracaoBoleto.pesquisar_configuracao_boleto, 
        name='pesquisar_configuracao_boleto'),
    url(r'^obter_campos_configuracao_boleto$', viewConfiguracaoBoleto.obter_campos_configuracao_boleto, 
        name='obter_campos_configuracao_boleto'),
    # Boleto Bancario
    url(r'^novo_boleto_bancario$', viewBoletoBancario.novo_boleto_bancario, name='novo_boleto_bancario'),
    url(r'^gerar_boleto$', viewBoletoBancario.gerar_boleto, name='gerar_boleto'),
    url(r'^obter_boleto_pdf$', viewBoletoBancario.obter_boleto_pdf, name='obter_boleto_pdf'),
    url(r'^enviar_boleto_email$', viewBoletoBancario.enviar_boleto_email, name='enviar_boleto_email'),
    # Remessa
    url(r'^retorno$', viewRetorno.retorno, name='retorno'),
    url(r'^gerar_remessa$', viewRemessa.gerar_remessa, name='gerar_remessa'),
    url(r'^gerar_retorno$', viewRetorno.gerar_retorno, name='gerar_retorno'),
    url(r'^download_arquivo_remessa$', viewRemessa.download_arquivo_remessa, name='download_arquivo_remessa'),
    url(r'^download_relatorio_remessa$', viewRemessa.download_relatorio_remessa, 
        name='download_relatorio_remessa'),
    url(r'^download_relatorio_retorno$', viewRetorno.download_relatorio_retorno, 
        name='download_relatorio_retorno'),
    # Login cliente
    url(r'^login_cliente$', viewLogin.login_cliente, name='login_cliente'),
    url(r'^novo_cadastro_cliente$', viewUsuario.novo_cadastro_cliente, name='novo_cadastro_cliente'),
    url(r'^cadastrar_novo_cliente$', viewUsuario.cadastrar_novo_cliente, name='cadastrar_novo_cliente'),
    url(r'^login_view_cliente$', viewLogin.login_view_cliente, name='login_view_cliente'),
    #url(r'^home_cliente$', viewHomeCliente.home_cliente, name='home_cliente'),
    url(r'^consultar_cpf_cnpj$', viewUsuario.consultar_cpf_cnpj, name='consultar_cpf_cnpj'),
    # Boleto Cliente
    #url(r'^segunda_via_boleto$', viewBoletoBancario.segunda_via_boleto, name='segunda_via_boleto'),
    #url(r'^pesquisar_boleto_cliente$', viewBoletoBancario.pesquisar_boleto_cliente, 
    #    name='pesquisar_boleto_cliente'),
    #url(r'^obter_campos_boleto_cliente$', viewBoletoBancario.obter_campos_boleto_cliente, 
    #    name='obter_campos_boleto_cliente'),
    #url(r'^filtrar_boleto_bancario_geracao$', viewBoletoBancario.filtrar_boleto_bancario_geracao, 
    #    name='filtrar_boleto_bancario_geracao'),
    #url(r'^obter_campos_boleto$', viewBoletoBancario.obter_campos_boleto, name='obter_campos_boleto'),
    # Motivo Inventário
    url(r'^motivo_inventario$', viewMotivoInventario.motivo_inventario, name='motivo_inventario'),
    url(r'^novo_motivo_inventario$', viewMotivoInventario.novo_motivo_inventario, 
        name='novo_motivo_inventario'),
    url(r'^cadastrar_motivo_inventario$', viewMotivoInventario.cadastrar_motivo_inventario, 
        name='cadastrar_motivo_inventario'),
    url(r'^inativar_motivo_inventario$', viewMotivoInventario.inativar_motivo_inventario, 
        name='inativar_motivo_inventario'),
    url(r'^pesquisar_motivo_inventario$', viewMotivoInventario.pesquisar_motivo_inventario, 
        name='pesquisar_motivo_inventario'),
    url(r'^obter_campos_motivo_inventario$',viewMotivoInventario.obter_campos_motivo_inventario, 
        name='obter_campos_motivo_inventario'),
    # Inventário
    url(r'^planilha_contagem$', viewInventario.planilha_contagem, name='planilha_contagem'),
    url(r'^pesquisar_estoque$', viewInventario.pesquisar_estoque, name='pesquisar_estoque'),
    url(r'^obter_campos_estoque$',viewInventario.obter_campos_estoque, name='obter_campos_estoque'),
    url(r'^obter_lista_estoque$',viewInventario.obter_lista_estoque, name='obter_lista_estoque'),
    url(r'^digitacao_inventario$',viewInventario.digitacao_inventario, name='digitacao_inventario'),
    url(r'^cadastrar_digitacao_inventario$',viewInventario.cadastrar_digitacao_inventario, 
        name='cadastrar_digitacao_inventario'),
    url(r'^editar_digitacao_inventario$',viewInventario.editar_digitacao_inventario, 
        name='editar_digitacao_inventario'),
    url(r'^finalizacao_inventario$',viewInventario.finalizacao_inventario, name='finalizacao_inventario'),
    url(r'^estorno_inventario$',viewInventario.estorno_inventario, name='estorno_inventario'),
    url(r'^cadastrar_finalizacao_inventario$',viewInventario.cadastrar_finalizacao_inventario, 
        name='cadastrar_finalizacao_inventario'),
    url(r'^cadastrar_estorno_inventario$',viewInventario.cadastrar_estorno_inventario, 
        name='cadastrar_estorno_inventario'),
    url(r'^obter_relatorio_finalizacao_estoque$',viewInventario.obter_relatorio_finalizacao_estoque, 
        name='obter_relatorio_finalizacao_estoque'),
    url(r'^relatorio_inventarios_digitados$', viewInventario.relatorio_inventarios_digitados, 
        name='relatorio_inventarios_digitados'),
    # Cheque
    url(r'^verificar_cheque$', viewCheque.verificar_cheque, name='verificar_cheque'),
    # Personalizações do Usuário
    url(r'^obter_campos_pesquisa_personalizados$', viewPersonalizacoes.obter_campos_pesquisa_personalizados, 
        name='obter_campos_pesquisa_personalizados'),
    url(r'^gravar_campos_pesquisa_personalizados$', viewPersonalizacoes.gravar_campos_pesquisa_personalizados, 
        name='gravar_campos_pesquisa_personalizados'),
    url(r'^excluir_campos_pesquisa_personalizados$', 
        viewPersonalizacoes.excluir_campos_pesquisa_personalizados, 
        name='excluir_campos_pesquisa_personalizados'),    
    # Carta Correção
    url(r'^nova_carta_correcao$', viewCartaCorrecao.nova_carta_correcao, name='nova_carta_correcao'),
    url(r'^filtrar_nota_fiscal$', viewCartaCorrecao.filtrar_nota_fiscal, name='filtrar_nota_fiscal'),
    url(r'^cadastrar_emitir_carta_correcao$', viewCartaCorrecao.cadastrar_emitir_carta_correcao, 
        name='cadastrar_emitir_carta_correcao'),
    url(r'^filtrar_carta_correcao$', viewCartaCorrecao.filtrar_carta_correcao, name='filtrar_carta_correcao'),
    url(r'^obter_carta_pdf$', viewCartaCorrecao.obter_carta_pdf, name='obter_carta_pdf'),
    url(r'^enviar_carta_email$', viewCartaCorrecao.enviar_carta_email, name='enviar_carta_email'),
    # Módulo
    url(r'^modulo$', viewModulo.modulo, name='modulo'),
    url(r'^novo_modulo$', viewModulo.novo_modulo, name='novo_modulo'),
    url(r'^cadastrar_modulo$', viewModulo.cadastrar_modulo, name='cadastrar_modulo'),
    url(r'^inativar_modulos$', viewModulo.inativar_modulos, name='inativar_modulos'),
    url(r'^pesquisar_modulo$', viewModulo.pesquisar_modulo, name='pesquisar_modulo'),
    url(r'^obter_campos_modulo$', viewModulo.obter_campos_modulo, name="obter_campos_modulo"),
    # Estado
    url(r'^estado$', viewEstado.estado, name='estado'),
    url(r'^novo_estado$', viewEstado.novo_estado, name='novo_estado'),
    url(r'^cadastrar_estado$', viewEstado.cadastrar_estado, name='cadastrar_estado'),
    url(r'^inativar_estados$', viewEstado.inativar_estados, name='inativar_estados'),
    url(r'^pesquisar_estado$', viewEstado.pesquisar_estado, name='pesquisar_estado'),
    url(r'^obter_campos_estado$', viewEstado.obter_campos_estado, name="obter_campos_estado"),
    # Cidades
    url(r'^cidade$', viewCidade.cidade, name='cidade'),
    url(r'^nova_cidade$', viewCidade.nova_cidade, name='nova_cidade'),
    url(r'^cadastrar_cidade$', viewCidade.cadastrar_cidade, name='cadastrar_cidade'),
    url(r'^inativar_cidades$', viewCidade.inativar_cidades, name='inativar_cidades'),
    url(r'^pesquisar_cidade$', viewCidade.pesquisar_cidade, name='pesquisar_cidade'),
    url(r'^listar_cidade$', viewCidade.listar_cidade, name='listar_cidade'),
    url(r'^obter_campos_cidade$', viewCidade.obter_campos_cidade, name="obter_campos_cidade"),
    # Regioes
    url(r'^regiao$', viewRegiao.regiao, name='regiao'),
    url(r'^nova_regiao$', viewRegiao.nova_regiao, name='nova_regiao'),
    url(r'^cadastrar_regiao$', viewRegiao.cadastrar_regiao, name='cadastrar_regiao'),
    url(r'^inativar_regioes$', viewRegiao.inativar_regioes, name='inativar_regioes'),
    url(r'^pesquisar_regiao$', viewRegiao.pesquisar_regiao, name='pesquisar_regiao'),
    url(r'^obter_campos_regiao$', viewRegiao.obter_campos_regiao, name="obter_campos_regiao"),
    # Áreas
    url(r'^area$', viewArea.area, name='area'),
    url(r'^nova_area$', viewArea.nova_area, name='nova_area'),
    url(r'^cadastrar_area$', viewArea.cadastrar_area, name='cadastrar_area'),
    url(r'^inativar_areas$', viewArea.inativar_areas, name='inativar_areas'),
    url(r'^pesquisar_area$', viewArea.pesquisar_area, name='pesquisar_area'),
    url(r'^obter_campos_area$', viewArea.obter_campos_area, name="obter_campos_area"),
    # Países
    url(r'^pais$', viewPais.pais, name='pais'),
    url(r'^novo_pais$', viewPais.novo_pais, name='novo_pais'),
    url(r'^cadastrar_pais$', viewPais.cadastrar_pais, name='cadastrar_pais'),
    url(r'^inativar_paises$', viewPais.inativar_paises, name='inativar_paises'),
    url(r'^pesquisar_pais$', viewPais.pesquisar_pais, name='pesquisar_pais'),
    url(r'^obter_campos_pais$', viewPais.obter_campos_pais, name="obter_campos_pais"), 
    # Relatorio de vendas por produto
    url(r'^relatorio_vendas_produto$', viewVendasProduto.relatorio_vendas_produto, 
        name='relatorio_vendas_produto'),
    url(r'^filtrar_relatorio_vendas_produto$', viewVendasProduto.filtrar_relatorio_vendas_produto, 
        name='filtrar_relatorio_vendas_produto'),
    # Tela inicial do modo de gerência de licenças de uso
    url(r'^lista_empresas_gerenciador_licencas$', viewEmpresaAdministrativo.lista_empresas_gerenciador_licencas,
        name='lista_empresas_gerenciador_licencas'),
    url(r'^pesquisar_empresa_gerenciador_licencas$', 
        viewEmpresaAdministrativo.pesquisar_empresa_gerenciador_licencas,
        name='pesquisar_empresa_gerenciador_licencas'),
    url(r'^obter_campos_gerenciador_licencas$', viewEmpresaAdministrativo.obter_campos_gerenciador_licencas,
        name='obter_campos_gerenciador_licencas'),
    url(r'^editar_licenca_empresa$', viewEmpresaAdministrativo.editar_licenca_empresa, 
        name='editar_licenca_empresa'),
    url(r'^atualizar_licenca_empresa$', viewEmpresaAdministrativo.atualizar_licenca_empresa, 
        name='atualizar_licenca_empresa'),
    # Mensagens da tela "fale conosco"
    url(r'^mensagens_fale_conosco$', viewFaleConosco.mensagens_fale_conosco, name='mensagens_fale_conosco'),
    url(r'^exibir_mensagens_fale_conosco$', viewFaleConosco.exibir_mensagens_fale_conosco, 
        name='exibir_mensagens_fale_conosco'),
    url(r'^pesquisar_mensagens_fale_conosco$', viewFaleConosco.pesquisar_mensagens_fale_conosco, 
        name='pesquisar_mensagens_fale_conosco'),
    url(r'^obter_campos_mensagens_fale_conosco$', viewFaleConosco.obter_campos_mensagens_fale_conosco, 
        name="obter_campos_mensagens_fale_conosco"),
    url(r'^resposta_mensagem_fale_conosco$', viewFaleConosco.resposta_mensagem_fale_conosco, 
        name='resposta_mensagem_fale_conosco'),
    # Fluxo de Caixa
    url(r'^fluxo_caixa_realizar$', viewFluxoCaixa.fluxo_caixa_realizar, name="fluxo_caixa_realizar"),
    url(r'^filtrar_fluxo_caixa_realizar$', viewFluxoCaixa.filtrar_fluxo_caixa_realizar, 
        name="filtrar_fluxo_caixa_realizar"),
    url(r'^fluxo_caixa_realizado$', viewFluxoCaixa.fluxo_caixa_realizado, name="fluxo_caixa_realizado"),
    url(r'^filtrar_fluxo_caixa_realizado$', viewFluxoCaixa.filtrar_fluxo_caixa_realizado, 
        name="filtrar_fluxo_caixa_realizado"),
    # Cadastro de Telas 
    url(r'^tela$', viewTela.tela, name='tela'),
    url(r'^nova_tela$', viewTela.nova_tela, name='nova_tela'),
    url(r'^cadastrar_tela$', viewTela.cadastrar_tela, name='cadastrar_tela'),
    url(r'^pesquisar_tela$', viewTela.pesquisar_tela, name='pesquisar_tela'),
    url(r'^obter_campos_tela$', viewTela.obter_campos_tela, name="obter_campos_tela"),
    # Áreas
    url(r'^especie$', viewEspecie.especie, name='especie'),
    url(r'^nova_especie$', viewEspecie.nova_especie, name='nova_especie'),
    url(r'^cadastrar_especie$', viewEspecie.cadastrar_especie, name='cadastrar_especie'),
    url(r'^inativar_especie$', viewEspecie.inativar_especie, name='inativar_especie'),
    url(r'^pesquisar_especie$', viewEspecie.pesquisar_especie, name='pesquisar_especie'),
    url(r'^obter_campos_especie$', viewEspecie.obter_campos_especie, name="obter_campos_especie"),
    # Contato
    url(r'^contato_dados$', viewContatoDados.contato_dados, name='contato_dados'),
    url(r'^novo_contato_dados$', viewContatoDados.novo_contato_dados, name='novo_contato_dados'),
    url(r'^cadastrar_contato_dados$', viewContatoDados.cadastrar_contato_dados, name='cadastrar_contato_dados'),
    url(r'^inativar_contato_dados$', viewContatoDados.inativar_contato_dados, name='inativar_contato_dados'),
    url(r'^pesquisar_contato_dados$', viewContatoDados.pesquisar_contato_dados, name='pesquisar_contato_dados'),
    url(r'^obter_campos_contato_dados$', viewContatoDados.obter_campos_contato_dados, 
        name='obter_campos_contato_dados'),
    # URLs do Bismart
    url(r'^login_bismart$', viewBismart.login_bismart, name='login_bismart'),
    url(r'^criar_usuario_bismart$', viewBismart.criar_usuario_bismart, name='criar_usuario_bismart'),
    url(r'^maiores_clientes_dia_mes$', viewBismart.maiores_clientes_dia_mes, name='maiores_clientes_dia_mes'),
    url(r'^vendas_anual$', viewBismart.vendas_anual, name='vendas_anual'),
    #url(r'^produtos_mais_vendidos_dia_mes$', viewBismart.produtos_mais_vendidos_dia_mes, 
    #   name='produtos_mais_vendidos_dia_mes'),
    url(r'^filtrar_produtos_bismart$', viewBismart.filtrar_produtos_bismart, name='filtrar_produtos_bismart'),
    url(r'^relatorio_vendedores$', viewBismart.relatorio_vendedores, name='relatorio_vendedores'),
    url(r'^relatorio_vendas_dia_mes$', viewBismart.relatorio_vendas_dia_mes, name='relatorio_vendas_dia_mes'),
    url(r'^relatorio_vendas_dia_mes_completo$', viewBismart.relatorio_vendas_dia_mes_completo, 
        name='relatorio_vendas_dia_mes_completo'),
    url(r'^envio_codigo_recuperacao$', viewBismart.envio_codigo_recuperacao, name='envio_codigo_recuperacao'),
    url(r'^verificar_codigo_recuperacao_senha$', viewBismart.verificar_codigo_recuperacao_senha, 
        name='verificar_codigo_recuperacao_senha'),
    url(r'^alterar_senha_bismart$', viewBismart.alterar_senha_bismart, name='alterar_senha_bismart'),
    url(r'^vendas_do_mes$', viewRelatorioNotaFiscalEntradaSaida.vendas_do_mes, name='vendas_do_mes'),
    url(r'^filtrar_financas_bismart$', viewBismart.filtrar_financas_bismart, name='filtrar_financas_bismart'),
    url(r'^politica_privacidade$', viewBismart.politica_privacidade, name='politica_privacidade'),
    url(r'^politica_privacidade_cardapioshow$', viewHome.politica_privacidade_cardapioshow, 
        name='politica_privacidade_cardapioshow'),        
    # urls do cardapioshow
    url(r'^cardapioshow$', viewCardapioShow.cardapioshow, name='cardapioshow'),
    url(r'^home_cardapioshow$', viewCardapioShow.home_cardapioshow, name='home_cardapioshow'),
    url(r'^pesquisar_promocao$', viewCardapioShow.pesquisar_promocao, name='pesquisar_promocao'),
    url(r'^baixar_cupons$', viewCardapioShow.baixar_cupons, name='baixar_cupons'),
    url(r'^mesas$', viewMesas.mesas, name='mesas'),
    url(r'^mesas_em_uso$', viewMesas.mesas_em_uso, name='mesas_em_uso'),
    url(r'^gravar_novo_pedido_mesa$', viewMesas.gravar_novo_pedido_mesa, name='gravar_novo_pedido_mesa'),
    url(r'^novo_pedido_mesa$', viewMesas.novo_pedido_mesa, name='novo_pedido_mesa'),
    url(r'^cancelar_pedido_mesa$', viewMesas.cancelar_pedido_mesa, name='cancelar_pedido_mesa'),
    # urls do coleta
    url(r'^coleta$', viewColeta.coleta, name='coleta'),
    url(r'^home_coleta$', viewColeta.home_coleta, name='home_coleta'),
    #url(r'^coleta/login$', viewCardapioShow.home_cardapioshow, name='home_cardapioshow'),
    # urls de ordem de serviço
    url(r'^ordem_servico$', viewOrdemServico.ordem_servico, name='ordem_servico'),
    url(r'^nova_ordem_servico$', viewOrdemServico.nova_ordem_servico, name='nova_ordem_servico'),
    url(r'^cadastrar_ordem_servico$', viewOrdemServico.cadastrar_ordem_servico, name='cadastrar_ordem_servico'),
    url(r'^pesquisar_ordem_servico$', viewOrdemServico.pesquisar_ordem_servico, name='pesquisar_ordem_servico'),
    url(r'^obter_campos_ordem_servico$', viewOrdemServico.obter_campos_ordem_servico, 
        name='obter_campos_ordem_servico'),
    url(r'^coleta_ordem_servico$', viewOrdemServico.coleta_ordem_servico, name='coleta_ordem_servico'),
    url(r'^entrega_ordem_servico$', viewOrdemServico.entrega_ordem_servico, name='entrega_ordem_servico'),
    url(r'^lancar_coleta_ordem_servico$', viewOrdemServico.lancar_coleta_ordem_servico, 
        name='lancar_coleta_ordem_servico'),
    url(r'^lancar_entrega_ordem_servico$', viewOrdemServico.lancar_entrega_ordem_servico, 
        name='lancar_entrega_ordem_servico'),
    # urls de tipos de serviço
    url(r'^tipo_servico$', viewTipoServico.tipo_servico, name='tipo_servico'),
    url(r'^novo_tipo_servico$', viewTipoServico.novo_tipo_servico, name='novo_tipo_servico'),
    url(r'^cadastrar_tipo_servico$', viewTipoServico.cadastrar_tipo_servico, name='cadastrar_tipo_servico'),
    url(r'^inativar_tipo_servico$', viewTipoServico.inativar_tipo_servico, name='inativar_tipo_servico'),
    url(r'^pesquisar_tipo_servico$', viewTipoServico.pesquisar_tipo_servico, name='pesquisar_tipo_servico'),
    url(r'^obter_campos_tipo_servico$', viewTipoServico.obter_campos_tipo_servico, 
        name='obter_campos_tipo_servico'),
    url(r'^obter_tipos_servico$', viewTipoServico.obter_tipos_servico, name='obter_tipos_servico'),
    # urls dos pontos de coleta/entrega
    url(r'^ponto_coleta_entrega$', viewPontoColEnt.ponto_coleta_entrega, name='ponto_coleta_entrega'),
    url(r'^novo_ponto_coleta_entrega$', viewPontoColEnt.novo_ponto_coleta_entrega, 
        name='novo_ponto_coleta_entrega'),
    url(r'^cadastrar_ponto_coleta_entrega$', viewPontoColEnt.cadastrar_ponto_coleta_entrega, 
        name='cadastrar_ponto_coleta_entrega'),
    url(r'^inativar_ponto_coleta_entrega$', viewPontoColEnt.inativar_ponto_coleta_entrega, 
        name='inativar_ponto_coleta_entrega'),
    url(r'^pesquisar_ponto_coleta_entrega$', viewPontoColEnt.pesquisar_ponto_coleta_entrega, 
        name='pesquisar_ponto_coleta_entrega'),
    url(r'^obter_campos_ponto_coleta_entrega$', viewPontoColEnt.obter_campos_ponto_coleta_entrega, 
        name='obter_campos_ponto_coleta_entrega'),
    # Forma de Entrega
    url(r'^forma_entrega$', viewFormaEntrega.forma_entrega, name='forma_entrega'),
    url(r'^nova_forma_entrega$', viewFormaEntrega.nova_forma_entrega, name='nova_forma_entrega'),
    url(r'^cadastrar_forma_entrega$', viewFormaEntrega.cadastrar_forma_entrega, 
        name='cadastrar_forma_entrega'),
    url(r'^inativar_formas_entrega$', viewFormaEntrega.inativar_formas_entrega, 
        name='inativar_formas_entrega'),
    url(r'^pesquisar_forma_entrega$', viewFormaEntrega.pesquisar_forma_entrega, 
        name='pesquisar_forma_entrega'),
    url(r'^obter_campos_forma_entrega$', viewFormaEntrega.obter_campos_forma_entrega, 
        name='obter_campos_forma_entrega'),
    # Forma de Pagamento
    url(r'^forma_pagamento$', viewFormaPagamento.forma_pagamento, name='forma_pagamento'),
    url(r'^nova_forma_pagamento$', viewFormaPagamento.nova_forma_pagamento, name='nova_forma_pagamento'),
    url(r'^cadastrar_forma_pagamento$', viewFormaPagamento.cadastrar_forma_pagamento, 
        name='cadastrar_forma_pagamento'),
    url(r'^inativar_formas_pagamento$', viewFormaPagamento.inativar_formas_pagamento, 
        name='inativar_formas_pagamento'),
    url(r'^pesquisar_forma_pagamento$', viewFormaPagamento.pesquisar_forma_pagamento, 
        name='pesquisar_forma_pagamento'),
    url(r'^obter_campos_forma_pagamento$', viewFormaPagamento.obter_campos_forma_pagamento, 
        name='obter_campos_forma_pagamento'),
    # Setores
    url(r'^setor$', viewSetor.setor, name='setor'),
    url(r'^novo_setor$', viewSetor.novo_setor, name='novo_setor'),
    url(r'^cadastrar_setor$', viewSetor.cadastrar_setor, name='cadastrar_setor'),
    url(r'^inativar_setor$', viewSetor.inativar_setor, name='inativar_setor'),
    url(r'^pesquisar_setor$', viewSetor.pesquisar_setor, name='pesquisar_setor'),
    url(r'^obter_campos_setor$', viewSetor.obter_campos_setor, name='obter_campos_setor'),
    # urls MegaZap
    url(r'^webchat$', viewChat.webchat, name='webchat'), # será removido em breve
    url(r'^megazap$', viewChat.megazap, name='megazap'),
    url(r'^chat$', viewChat.chat, name='chat'),
    url(r'^obter_pendentes$', viewChat.obter_pendentes, name='obter_pendentes'),
    url(r'^obter_ativos$', viewChat.obter_ativos, name='obter_ativos'),
    url(r'^obter_atendentes$', viewChat.obter_atendentes, name='obter_atendentes'),
    url(r'^atender_chat$', viewChat.atender_chat, name='atender_chat'), 
    url(r'^encaminhar_chat$', viewChat.encaminhar_chat, name='encaminhar_chat'), 
    url(r'^finalizar_chat$', viewChat.finalizar_chat, name='finalizar_chat'), 
    url(r'^responder_chat$', viewChat.responder_chat, name='responder_chat'), 
    url(r'^obter_mensagens$', viewChat.obter_mensagens, name='obter_mensagens'), 
    url(r'^obter_anexo_msg$', viewChat.obter_anexo_msg, name='obter_anexo_msg'), 
    url(r'^obter_historico$', viewChat.obter_historico, name='obter_historico'), 
    url(r'^enviar_anexo$', viewChat.enviar_anexo, name='enviar_anexo'), 
    url(r'^obter_dados_finalizacao$', viewChat.obter_dados_finalizacao, name='obter_dados_finalizacao'), 
    url(r'^grafico_atendimentos$', viewChat.grafico_atendimentos, name='grafico_atendimentos'), 
    url(r'^filtrar_atendimentos_megazap$', viewChat.filtrar_atendimentos_megazap, 
        name='filtrar_atendimentos_megazap'),
    url(r'^relatorio_agendamentos$', viewChat.relatorio_agendamentos, name='relatorio_agendamentos'),
    url(r'^filtrar_agendamentos$', viewChat.filtrar_agendamentos, name='filtrar_agendamentos'),
    url(r'^grafico_agendamentos$', viewChat.grafico_agendamentos, name='grafico_agendamentos'),
    url(r'^obter_dados_grafico_agendamentos$', viewChat.obter_dados_grafico_agendamentos, name='obter_dados_grafico_agendamentos'),
    url(r'^disparar_mensagem$', viewChat.disparar_mensagem, name='disparar_mensagem'),
    url(r'^enviar_msg_disparo$', viewChat.enviar_msg_disparo, name='enviar_msg_disparo'),
    url(r'^enviar_anexo_disparo$', viewChat.enviar_anexo_disparo, name='enviar_anexo_disparo'),
    url(r'^filtrar_contatos$', viewChat.filtrar_contatos, name='filtrar_contatos'),
    # Comentários
    url(r'^cadastrar_comentario$', viewComentarioProduroPedido.cadastrar_comentario, 
        name='cadastrar_comentario'),
    url(r'^inativar_comentarios$', viewComentarioProduroPedido.inativar_comentarios, 
        name='inativar_comentarios'),
    url(r'^pesquisar_comentario$', viewComentarioProduroPedido.pesquisar_comentario, 
        name='pesquisar_comentario'),
    url(r'^obter_campos_comentario$', viewComentarioProduroPedido.obter_campos_comentario, 
        name='obter_campos_comentario'),
    # urls api do PortalERP
    url(r'^api/login$', viewApi.login, name='login_api'),
    url(r'^api/listar$', viewApi.listar, name='listar'),
    url(r'^api/criar$', viewApi.criar, name='criar'),
    url(r'^api/editar$', viewApi.editar, name='editar'),
    url(r'^api/inativar$', viewApi.inativar, name='inativar'),
    url(r'^api/enviar_email_recuperacao_senha$', viewApi.enviar_email_recuperacao_senha, 
        name='enviar_email_recuperacao_senha'),
    url(r'^api/verificar_codigo_recuperacao_senha$', viewApi.verificar_codigo_recuperacao_senha, 
        name='verificar_codigo_recuperacao_senha'),
    url(r'^api/alterar_senha_acesso_app$', viewApi.alterar_senha_acesso_app, name='alterar_senha_acesso_app'),
    # as urls abaixo, do grupo de urls da api serão definidas para testes. Favor, excluí-las assim que os
    url(r'^opcionais_de_testes$', viewOpcionaisTestes.opcional, name='opcionais_de_testes'),
    url(r'^pesquisar_opcionaisTestes$', viewOpcionaisTestes.pesquisar_opcionaisTestes, name='pesquisar_opcionaisTestes'),
    url(r'^obter_campos_opcionaisTestes$', viewOpcionaisTestes.obter_campos_opcionaisTestes, name='obter_campos_opcionaisTestes'),
    url(r'^filtrar_relatorio_opcionaisTestes$', viewOpcionaisTestes.filtrar_relatorio_opcionaisTestes, 
        name='filtrar_relatorio_opcionaisTestes'),

    # testes da rotina de integração com o esoft terminarem
    url(r'^inventario/produtos$', viewApi.inventario_produtos, name='inventario_produtos'),
    url(r'^inventario/funcionarios$', viewApi.inventario_funcionarios, name='inventario_funcionarios'),
    url(r'^inventario/producoes$', viewApi.inventario_producoes, name='inventario_producoes'),
    url(r'^inventario/status$', viewApi.inventario_status, name='inventario_status'),
    url(r'^inventario/excaponta$', viewApi.inventario_excaponta, name='inventario_excaponta'),
    url(r'^inventario/addaponta$', viewApi.inventario_addaponta, name='inventario_addaponta'),
    url(r'^inventario/producao.+$', viewApi.inventario_producao, name='inventario_producao'),
    #urls do dashboard
    url(r'^login_dashboard$', viewLogin.login_dashboard, name='login_dashboard'),
    url(r'^empresa_usuario_dashboard$', viewEmpresa.empresa_usuario_dashboard, 
        name='empresa_usuario_dashboard'),    
    # urls de aplicativos
    url(r'^aplicativo$', viewAplicativo.aplicativo, name='aplicativo'),
    url(r'^novo_aplicativo$', viewAplicativo.novo_aplicativo, name='novo_aplicativo'),
    url(r'^cadastrar_aplicativo$', viewAplicativo.cadastrar_aplicativo, name='cadastrar_aplicativo'),
    url(r'^inativar_aplicativo$', viewAplicativo.inativar_aplicativo, name='inativar_aplicativo'),
    url(r'^pesquisar_aplicativo$', viewAplicativo.pesquisar_aplicativo, name='pesquisar_aplicativo'),
    url(r'^obter_campos_aplicativo$', viewAplicativo.obter_campos_aplicativo, name='obter_campos_aplicativo'),
    # urls de lojas
    url(r'^loja$', viewLoja.loja, name='loja'),
    url(r'^nova_loja$', viewLoja.nova_loja, name='nova_loja'),
    url(r'^cadastrar_loja$', viewLoja.cadastrar_loja, name='cadastrar_loja'),
    url(r'^inativar_loja$', viewLoja.inativar_loja, name='inativar_loja'),
    url(r'^pesquisar_loja$', viewLoja.pesquisar_loja, name='pesquisar_loja'),
    url(r'^obter_campos_loja$', viewLoja.obter_campos_loja, name='obter_campos_loja'),
    # Apontamento Produção
    url(r'^apontamento_producao$', viewApontamentoProducao.apontamento_producao, name='apontamento_producao'),
    url(r'^novo_apontamento_producao$', viewApontamentoProducao.novo_apontamento_producao, 
        name='novo_apontamento_producao'),
	url(r'^cadastrar_apontamento_producao$', viewApontamentoProducao.cadastrar_apontamento_producao, 
        name='cadastrar_apontamento_producao'),
	url(r'^filtrar_apontamento_producao$', viewApontamentoProducao.filtrar_apontamento_producao, 
        name='filtrar_apontamento_producao'),
    url(r'^relatorio_apontamento_producao$', viewApontamentoProducao.relatorio_apontamento_producao,
        name='relatorio_apontamento_producao'),
    url(r'^pesquisar_itens$', viewApontamentoProducao.pesquisar_itens, name='pesquisar_itens'),
    url(r'^obter_campos_itens$', viewApontamentoProducao.obter_campos_itens, name='obter_campos_itens'),
    url(r'^rotina_envio_api_esoft$', viewApontamentoProducao.rotina_envio_api_esoft, 
        name='rotina_envio_api_esoft'),
    # Categorias
    url(r'^categoria$', viewCategoria.categoria, name='categoria'),
    url(r'^nova_categoria$', viewCategoria.nova_categoria, name='nova_categoria'),
    url(r'^cadastrar_categoria$', viewCategoria.cadastrar_categoria, name='cadastrar_categoria'),
    url(r'^vincula_loja$', viewCategoria.vincula_loja, name='vincula_loja'),
    url(r'^get_hierarquia_categorias$', viewCategoria.get_hierarquia_categorias,
        name='get_hierarquia_categorias'),
    url(r'^inativar_categoria$', viewCategoria.inativar_categoria, name='inativar_categoria'),
    url(r'^pesquisar_categoria$', viewCategoria.pesquisar_categoria, name='pesquisar_categoria'),
    # Status de finalização de atendimento
    url(r'^status_finalizacao$', viewStatusFinalizacao.status_finalizacao, name='status_finalizacao'),
    url(r'^novo_status_finalizacao$', viewStatusFinalizacao.novo_status_finalizacao, name='novo_status_finalizacao'),
    url(r'^cadastrar_status_finalizacao$', viewStatusFinalizacao.cadastrar_status_finalizacao, name='cadastrar_status_finalizacao'),
    url(r'^inativar_status_finalizacao$', viewStatusFinalizacao.inativar_status_finalizacao, name='inativar_status_finalizacao'),
    url(r'^pesquisar_status_finalizacao$', viewStatusFinalizacao.pesquisar_status_finalizacao, name='pesquisar_status_finalizacao'),
    url(r'^obter_campos_status_finalizacao$', viewStatusFinalizacao.obter_campos_status_finalizacao, name='obter_campos_status_finalizacao'),
    url(r'^consultar_status_finalizacao$', viewStatusFinalizacao.consultar_status_finalizacao, name='consultar_status_finalizacao'),
    url(r'^verifica_status_finalizacao_existente$', viewStatusFinalizacao.verifica_status_finalizacao_existente, name='verifica_status_finalizacao_existente'),
    # Tipo de Atendimento
    url(r'^tipo_atendimento$', viewTipoAtendimento.tipo_atendimento, name='tipo_atendimento'),
    url(r'^novo_tipo_atendimento$', viewTipoAtendimento.novo_tipo_atendimento, name='novo_tipo_atendimento'),
    url(r'^cadastrar_tipo_atendimento$', viewTipoAtendimento.cadastrar_tipo_atendimento, name='cadastrar_tipo_atendimento'),
    url(r'^inativar_tipo_atendimento$', viewTipoAtendimento.inativar_tipo_atendimento, name='inativar_tipo_atendimento'),
    url(r'^pesquisar_tipo_atendimento$', viewTipoAtendimento.pesquisar_tipo_atendimento, name='pesquisar_tipo_atendimento'),
    url(r'^obter_campos_tipo_atendimento$', viewTipoAtendimento.obter_campos_tipo_atendimento, name='obter_campos_tipo_atendimento'),
    url(r'^consultar_tipo_atendimento$', viewTipoAtendimento.consultar_tipo_atendimento, name='consultar_tipo_atendimento'),
    # Magento
    url(r'^sincronizar_magento$', viewEmpresa.sincronizar_magento, name='sincronizar_magento'),
    url(r'^pesquisar_magento$', viewProduto.pesquisar_magento, name='pesquisar_magento'),
    url(r'^obter_campos_magento$', viewProduto.obter_campos_magento, name='obter_campos_magento'),
    url(r'^obter_campos_categorias_magento$', viewProduto.obter_campos_categorias_magento,
        name='obter_campos_categorias_magento'),
    url(r'^listar_atributos_magento$', viewGrupo.listar_atributos_magento, name='listar_atributos_magento'),
    url(r'^cadastrar_atributo_grupo_magento$', viewGrupo.cadastrar_atributo_grupo_magento,
        name='cadastrar_atributo_grupo_magento'),
    # AppBase Flutter
    url(r'^appbase$', viewAppBase.appbase, name='appbase'),
    url(r'^novo_appbase$', viewAppBase.novo_appbase, name='novo_appbase'),
    url(r'^cadastrar_appbase$', viewAppBase.cadastrar_appbase, name='cadastrar_appbase'),
    url(r'^inativar_appbase$', viewAppBase.inativar_appbase, name='inativar_appbase'),
    url(r'^pesquisar_appbase$', viewAppBase.pesquisar_appbase, name='pesquisar_appbase'),
    url(r'^obter_campos_appbase$', viewAppBase.obter_campos_appbase, name='obter_campos_appbase'),
    url(r'^pesquisar_appbase_ui$', viewAppBase.pesquisar_appbase_ui, name='pesquisar_appbase_ui'),
    url(r'^obter_campos_appbase_ui$', viewAppBase.obter_campos_appbase_ui, name='obter_campos_appbase_ui'),
    # Página de erro
    url(r'^pagina_licenca_vencida$', viewErro404.pagina_licenca_vencida, name='pagina_licenca_vencida'),
    url(r'.+', viewErro404.error404, name="erro"),
    url(r'^pagina_erro$', viewErro404.error404, name="pagina_erro")
]
